name: CI

on:
  push: {}

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install spreet
        run: cargo install spreet

      - name: Install dependencies
        run: bin/setup

      - name: Run tests
        run: npm run test
